# Generated by Django 6.1 on 2026-09-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_mpesapayment_ticket_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="booking",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
