# Generated by Django 6.1 on 2026-09-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_remove_ticket_booking_delete_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="screens",
                to="system.cinema",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="showtimes",
                to="system.movie",
            ),
        ),
    ]
