[project]
name = "reservation-system"
version = "0.1.0"
description = ""
authors = [
    {name = "j1mmy7z7",email = "jamesmuchiri792@yahoo.com"}
]
requires-python = ">=3.14,<4"
dependencies = [
    "djangorestframework (>=3.18.0,<4.0.0)",
    "django-environ (>=0.14.0,<0.15.0)",
    "psycopg[binary] (>=3.3.5,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
